### ISSUE TITLE
Docker and Codespaces

### ISSUE THREAD

**Issue by PariaNaghavi** [qir-alliance/qat#157]
It seems that building qat fails during the container image creation, resulting in the codespace opening in recovery mode. Please see here for the [Dockerfile](![image](https://user-images.githubusercontent.com/76576654/211096651-c798d278-2d6e-4ec1-937c-2e67f5bd6cfa.png)) we are using for the qir-book. Despite changing the llvm version to 14, this error persists.
<img width="1296" alt="Screen Shot 2022-12-30 at 13 01 19" src="https://user-images.githubusercontent.com/76576654/211097277-c4ede2ff-5bbc-4102-bfa8-d42178ba003b.png">

**Comment by stevescia** [comment]
I had trouble building with cmake as well; As an alternative, I was able to build and run the qat sample with bazel . I created a gist with the steps to build and run qat, which may be helpful to you: https://gist.github.com/stevescia/1b6eafce631f41c946f16093b69b994c#file-initial-qat-compile-and-test-rundown

**Comment by swernli** [comment]
@PariaNaghavi sorry for the very late response here. The Dockerfile checked into the repo still works for codespaces development using cmake to build. Are you still experiencing issues with the compilation? I don't see any recent PRs to qir-book that would indicate any updates to the workflow.
