### ISSUE TITLE
Support multiple values in entry-point-attr

### ISSUE THREAD

**Issue by jrj-d** [qir-alliance/qat#165]
pyqir, currently the main producer of QIR, changed the entry point label from "EntryPoint" to "entry_point" in version 0.8.0
(If anyone knows why this change was made, I'm interested.)

As result, a QAT target receiving indifferently QIR generated with old and newer versions of pyqir should support multiple entry point label values ("entry_point" and "EntryPoint").

One solution is to let `entry-point-attr` support multiple values as in:
```
spec:
  ...
  entry-point-attr: EntryPoint,entry_point
```

**Comment by swernli** [comment]
Hi @jrj-d, just getting around to these issues now. The update in PyQIR was motivated by an update to the QIR Base profile spec, which changed the official attribute to `entry_point`. For some clients, I've seen the catch-all approach of adding `EntryPoint` and `entry_point` to the corresponding attribute list, which works but requires the clients know to do this. I like your suggestion here, and I think it's something we can add.
