### ISSUE TITLE
Qat doesn't inline a function call even with --always-inline and --profile base specified

### ISSUE THREAD

**Issue by peter-campora** [qir-alliance/qat#52]
Hi, 

It seems like the --always-inline flag doesn't always force inlining in the generated QIR. I ran the following command via qat:
`./qat --always-inline --apply -S --profile base MagicStateDistillation-10X.ll > MagicStateDistillation-BaseProfile.10X.ll`
on the attached file and received the following output in MagicStateDistillation-BaseProfile.10X.ll (I changed the ll files to text files to attach them to the issue). The entry point function in the output file, `@Microsoft__Quantum__Samples__MeasureDistilledTAtDepth10InX__Interop`, calls out to  a helper function `@Microsoft__Quantum__Samples__Distill__body.4`. 

[MagicStateDistillation-10X.txt](https://github.com/qir-alliance/qat/files/7871641/MagicStateDistillation-10X.txt)
[MagicStateDistillation-BaseProfile.10X.txt](https://github.com/qir-alliance/qat/files/7871642/MagicStateDistillation-BaseProfile.10X.txt)

Let me know if I should try again with additional arguments to qat, or whether you need any more information.

**Comment by swernli** [comment]
Thanks for reporting, @peter-campora! We will investigate and see if we can find out what inline fails on that example.
@troelsfr FYI.

**Comment by troelsfr** [comment]
FYI, this issue should be solved in #53 - @swernli if you have time to review, then that would be much appreciated :)

**Comment by swernli** [comment]
Thanks @troelsfr for working on that! I'll review today.

**Comment by troelsfr** [comment]
#53 is merged and I am closing this ticket. @peter-campora feel free to reopen if this does not solve the issue for you.

**Comment by peter-campora** [comment]
I'll take a look a look at the new version of qat and test it out! Thanks all! I found a new issue, so I'll see if any updates fix this new issue and if not, I'll file a new issue.
