### ISSUE TITLE
Build instructions list src/Passes, but that folder is not in the repo.

### ISSUE THREAD

**Issue by cgranade** [qir-alliance/qat#56]
The build instructions at https://github.com/qir-alliance/qat/blob/main/docs/src/UserGuide/BuildingLibrary.md#build-instructions-for-users and at https://qir-alliance.github.io/qat/UserGuide/QuickStart/ both list that to build QAT, one needs to start by running `cd src/Passes` from the root of the repo. Doing so results in an error, as there is no such folder in the repo currently.

**Comment by troelsfr** [comment]
This comment is no longer relevant as `cd src/Passes` is no longer present in either of the documents.  A full review of all the documentation (issue #121) is meant to catch similar inconsistencies.
